spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_service_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: kafka:9092 #For docker-compose startup
#      bootstrap-servers: localhost:9092 #For IntelliJ Idea startup

  liquibase:
    change-log: db/changelog/changelog.yaml

jwt:
  secret_key: "secret"
  expires_in: 1000
  issuer: "creditService"

topic-name: "statisticsTopic"